version: "3.9"

services:
  # Django application - MyApp
  myapp:
    build:
      context: .
    container_name: myapp_container
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=BRD_dev.settings
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 BRD_dev.asgi:application
      "
    ports:
      - "8000:8000"
    depends_on:
      - BRD_DATABASE
      - redis_db
      - kafka
    restart: unless-stopped

  # Django application - Driver
  driver:
    build:
      context: .
    container_name: driver_container
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=BRD_dev.settings
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 BRD_dev.asgi:application
      "
    ports:
      - "8001:8000"  
    depends_on:
      - BRD_DATABASE_FOR_DRIVER
      - BRD_DATABASE
      - redis_db
    restart: unless-stopped


# Django application - admin
  dashboard:
    build:
      context: .
    container_name : dashboard_container  
    volumes:
     - .:/app
     - media_volume:/app/media
    env_file:
     - .env
    depends_on:
     - kafka
     - BRD_DATABASE
     - BRD_DATABASE_FOR_DRIVER
     - redis_db
    environment:
     - DJANGO_SETTINGS_MODULE=BRD_dev.settings
    command: >
     sh -c "
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 BRD_dev.asgi:application
     " 
    restart: unless-stopped
    ports:
     - "8002:8000"


  # Celery worker
  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A BRD_dev worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=BRD_dev.settings
    depends_on:
      - myapp
      - redis_db
      - BRD_DATABASE
    restart: unless-stopped

  # Celery beat
  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A BRD_dev beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=BRD_dev.settings
    depends_on:
      - myapp
      - celery_worker
      - redis_db
      - BRD_DATABASE
    restart: unless-stopped

  # PostgreSQL database
  BRD_DATABASE:
    image: postgres:15
    container_name: brd_DB_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5438:5432"
    restart: unless-stopped

  BRD_DATABASE_FOR_DRIVER:
    image: postgres:15
    container_name: driver_brd_DB_container
    volumes:
      - driver_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5439:5432"
    restart: unless-stopped  

  # Redis
  redis_db:
    image: redis:7
    container_name: redis_db
    ports:
      - "6077:6379"
    restart: unless-stopped

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-container
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - /home/shawon/Desktop/BRD_Frontend/brd/build/app/outputs/flutter-apk:/app/apk:ro
    depends_on:
      - myapp
      - driver
      - dashboard
    restart: unless-stopped


# Docker volumes
volumes:
  postgres_data:
  driver_postgres_data:
  zookeeper_data:
  kafka_data:
  media_volume:
