# Generated by Django 5.2.7 on 2026-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('describtions', models.TextField(blank=True, max_length=1000)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending')),
                ('DL_frontside', models.ImageField(upload_to='images/')),
                ('DL_Backside', models.ImageField(upload_to='images/')),
                ('NID_frontside', models.ImageField(upload_to='images/')),
                ('NID_backside', models.ImageField(upload_to='images/')),
                ('CV_field', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
