# Generated by Django 5.2.7 on 2026-01-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_drivermodel_cv_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmialOtp', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_otp', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.drivermodel')),
            ],
        ),
    ]
