# Generated by Django 5.2.7 on 2026-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driveremail_driverotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
