# Generated by Django 5.2.7 on 2026-01-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_drivermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveremail',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverotp',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
