# Generated by Django 5.2.7 on 2026-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driveremail_is_varified_driverotp_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveremail',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='driverotp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
