# Generated by Django 5.2.7 on 2026-01-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driveremail_email_driverotp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverotp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.drivermodel'),
        ),
    ]
