# Generated by Django 5.2.7 on 2026-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_alter_driverotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
