# Generated by Django 5.2.7 on 2026-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_alter_driverotp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveremail',
            name='attemps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverotp',
            name='attemps',
            field=models.IntegerField(default=0),
        ),
    ]
