# Generated by Django 5.2.7 on 2026-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driveremail_attemps_driverotp_attemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
