# Generated by Django 5.2.7 on 2026-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_drivermodel_is_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='DL_frontside',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
