# Generated by Django 5.2.7 on 2026-02-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_alter_drivermodel_dl_frontside'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='CV_field',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='DL_Backside',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='DL_frontside',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='NID_backside',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='NID_frontside',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtions', models.TextField(blank=True, max_length=1000)),
                ('DL_frontside', models.ImageField(default='images/default.png', upload_to='images/')),
                ('DL_Backside', models.ImageField(default=None, upload_to='images/')),
                ('NID_frontside', models.ImageField(default=None, upload_to='images/')),
                ('NID_backside', models.ImageField(default=None, upload_to='images/')),
                ('CV_field', models.ImageField(default=None, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
