# Generated by Django 5.2.7 on 2026-02-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_alter_driverprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
