# Generated by Django 5.2.7 on 2026-02-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_driverbookingmodel_driverconfirmationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverconfirmationmodel',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverconfirmationmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DriverBookingModel',
        ),
        migrations.DeleteModel(
            name='DriverConfirmationModel',
        ),
    ]
