# Generated by Django 5.2.7 on 2026-02-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_hireconfirmationmodel_is_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireconfirmationmodel',
            name='is_booked',
        ),
    ]
