# Generated by Django 5.2.7 on 2026-01-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userotp_emailotp_emailotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='PhoneOtp',
            new_name='EmialOtp',
        ),
    ]
