# Generated by Django 5.2.7 on 2026-01-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_forgetpasswordapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgetPasswordApi',
            new_name='ForgetPasswordModel',
        ),
    ]
