# Generated by Django 5.2.7 on 2026-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_forgetpasswordapi_forgetpasswordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordmodel',
            name='otp',
            field=models.CharField(max_length=6, null=6),
            preserve_default=6,
        ),
    ]
