# Generated by Django 5.2.7 on 2026-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_forgetpasswordmodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordmodel',
            name='attemps',
            field=models.IntegerField(default=0),
        ),
    ]
