# Generated by Django 5.2.7 on 2026-01-25 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_forgetpasswordmodel_attemps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, max_length=1000)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('working_hour', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
