# Generated by Django 5.2.7 on 2026-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_makeordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeordermodel',
            name='contact_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
