# Generated by Django 5.2.7 on 2026-02-08 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeordermodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
