# Generated by Django 5.2.7 on 2026-04-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_locationviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationviewmodel',
            name='location_name',
        ),
    ]
