# Generated by Django 5.2.7 on 2026-04-17 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_locationviewmodel_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationviewmodel',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
