# Generated by Django 5.2.7 on 2026-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_locationviewmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgetpasswordmodel',
            name='otp_varified',
            field=models.BooleanField(default=False),
        ),
    ]
