server {
    listen 80;

    # myapp
    location /myapp/ {
        rewrite ^/myapp(/.*)$ $1 break;
        proxy_pass http://myapp:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    # driver
    location /driver/ {
        rewrite ^/driver(/.*)$ $1 break;
        proxy_pass http://driver:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    # dashboard
    location /dashboard/ {
        rewrite ^/dashboard(/.*)$ $1 break;
        proxy_pass http://dashboard:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    location /media/ {
        alias /app/media/;
    }
    
}
