server {
    listen 80;

    # 🔥 ADD THIS HERE (before or after other locations is fine)
    location /ws/ {
        proxy_pass http://myapp:8000;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;

        proxy_read_timeout 86400;
    }

    # myapp
    location /myapp/ {
        rewrite ^/myapp(/.*)$ $1 break;
        proxy_pass http://myapp:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # driver
    location /driver/ {
        rewrite ^/driver(/.*)$ $1 break;
        proxy_pass http://driver:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # dashboard
    location /dashboard/ {
        rewrite ^/dashboard(/.*)$ $1 break;
        proxy_pass http://dashboard:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        alias /app/media/;
    }
}